version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NAME=Santiago
      - SURNAME=Lorca
      - DOCUMENT=30904465
      - BIRTHDAY=1999-03-17
      - NUMBER=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency-1.csv

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NAME=Lautaro Valentin
      - SURNAME=Forner√≥n
      - DOCUMENT=23772524
      - BIRTHDAY=1980-02-10
      - NUMBER=9955
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-2.csv:/agency-2.csv

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NAME=Emanuel
      - SURNAME=Soto
      - DOCUMENT=22069151
      - BIRTHDAY=2004-03-30
      - NUMBER=2979
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-3.csv:/agency-3.csv

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NAME=Nicolas Andres 
      - SURNAME=Huarte
      - DOCUMENT=29369913
      - BIRTHDAY=1989-12-05
      - NUMBER=6857
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-4.csv:/agency-4.csv

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NAME=Valentina
      - SURNAME=Vera
      - DOCUMENT=30170921
      - BIRTHDAY=1982-05-22
      - NUMBER=6053
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-5.csv:/agency-5.csv

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
